sudo: required
services:
- docker
language: go
go:
- '1.5'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Sv/J6pD0IzA2yLnJlug6UOsUhZOiGkg1Ho7+vUXruZh4iFpjjMzNm+Z3qckywD4gm1OzMGUduYs08bAZDhZ0/+4cpE5ErS1RCu1rUeaVdR9m1fBuES03gk82hiiLu+gAtSVgL7PZkjrOuDtH6Z141zesaXPo/q88DgoUPx8t2n5gFKjpDWStgHMSR0LRuZ8IxZ+wdZPjJrBEqefLD3LKDdpGR3wTNsN/15vz1uLxRtJkaxrIaUe8WsBS4W2BVk/xL5AjzGGt/brWT1bvP/8ymtEz5ZC2d3tVzj7Kzy9AA+uuUJSLguwfd2Vueo0ZQyqJ2mRKs3KsxJSc1YuPjigDKHCt20bVc7TX/BpSJdKzE2eskloCsQYM93YZrIob4NMKLeiBR/oe3+nzrTSFsa+ufqD34VktpgZ0I/m2FMigafJWwNkLZja4yPrvQh/X2Ki6PH6X0L4NamJ8uX77qKel+2l7H7KQz87laAuxQyF51nO06eudQsgCdnSnP7h5vrWGNY4ZMnHlQ9iZ53XEXqaDBSGA07/2qIH+cZSxi9WXjrU1AlblQAIxl2v7lnW3YpaSq4Md7Be0Lv9KoWGaKnLkMwZbOy1OkJ6LDGWa+AfzmIm7qoFEIOTHMi/2uIcAR2YbtoVYlXmFPodFza4pT+wFWK3Q/xTIAVxaIifLD/igpfY=
  - secure: wZWjUC1+iP8Vv2MCB4d8zx/cu+12MC9G9QTInj9TU1xyGeso+LIQIKJPcPXWicBad2HFvcuwvMOv7SKtHgGiIcq7/VbJRUBtUjUghO/zvue45L1Cr1apBXCUxROQpJd375j9if7YOBjBLGLJseGTVd/+sCpolIZW5QzEaN6mS4fCg8teaLsVck00ZGUmWzeSeYDaRlTgcCb6urnLlMSUMvl5j8OZNltwjjfWN10JN+Ihde8AX+FXJ5xz4ga7djaNHRir6L1gm0qc2P8pCMD8II+djTtlsFwsv4JZRJX5dlyVs377zTREPuSMXo1xNSgML5xegsd/HVT1cXbh+MP0qQuu//Tjr20HtF7yw7bWMyLTyuG6Uh14u28ehM1TVt5eLu7OPPZdTYs0U1vAO3DSvQJSGBvCBJ5GAl1kG/Nw7zhIJmFAORexrDMzOC/RGBAmt0orPRVOvJhaImjeTNd7UlNaU/NCMCVM+pvIVggRBJa6eNNn346tBSZobU9Xv+pzIOsxF28lUz+YpYcwEbOyQfu2x9accvOW4xtIYZhxca9LrVQkj0uHHG9Lrk1lqHVv9b9OAs+mOx0poLr6//WCyZ6DgZ+i10Fu6ZEl2z4ZCfkrFYnlzTBbq2EYqCmDbrBxl8QPnshRzzbmzPwVoX8xPvzcm3uEkW7IEXlTGXbRsJA=
  - secure: CPbnXhpzhZWqoYMMB3TZyxdcYCMrFX7ezL5Dl01nK5JWz5YhjtJoc+AMsvAHxbKLIrUroobzGAP+SkMgMK/j+aNgHF7QFUeS5/NW20d8cTTMf2/T+UbGIlvbTqVYhovJwjvwVFhb/Sz1qiR8JSossV84UtvBrXVlNs/xVglCrNOypsG16raj4XPbjDzeKESJuRkEewK/M1A9vSzHI6NGfXJSZD+KVJfHKT30XkaVbCzWOJ53LqyZgrjF63TkxEvFzsVfIpOhyQYotsggjIgEHnIkNf0ASEbKd9QplokqkM+4jKHV+kQLJa9NUd+SswSF1bfy/9UM/Iw2XVvNcaesxbKBzMGIHSCjEStkYJpyrYt0uv5qlgEfdAzqgfG67aNDNUyWyUceVcQ+qDgOXUPOPa2U9/I1c1ZNvo3eaio/1sPiTNjY89ObdfL+YNERigTHWWOpaI5yK7GKzT7/O79eFclaM1Y87a4BbmB8G0Zygyvy6LKnzS3sjmjbWp/dvIw9+txUoLI2dnsWK859ysXtmT1P1YrFPoGPtdPVGP0bn162LAxubj37eQJppLXtJDSyXIpX60Yq6rL8Tc/9EynFfvL0A7r6YG45wRRhlxCxLb/Idz5LUjHxzkw60RzMXapEaW40EeDExvdXEodHpJzK4A70VMkRFwOKsjYj+QYQh6c=
after_success:
- CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=nejch/fluentd-aws-elasticsearch
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
